[package]
name = "rff"
version = "0.1.0"
authors = ["YukiFujimatsu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.7" }
serde = "1.0.118"
serde_derive = "1.0.118"
serde_json = "1.0.60"
